# Generated by Django 4.2.5 on 2023-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
