# Generated by Django 4.2.5 on 2023-10-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('price', models.IntegerField(verbose_name=5)),
                ('location', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
